import type { SyndicationInputs } from '@dealforge/types';

export const SYNDICATION_DEFAULTS: SyndicationInputs = {
  // Capital Structure
  totalCapitalization: 5000000,
  lpEquityPercent: 90,
  gpEquityPercent: 10,

  // Fees
  acquisitionFeePercent: 2,
  assetManagementFeePercent: 1.5,

  // Preferred Return
  preferredReturnPercent: 8,

  // Waterfall Tiers
  tier2LpPercent: 70,
  tier2GpPercent: 30,
  tier2IrrHurdle: 12,
  tier3LpPercent: 60,
  tier3GpPercent: 40,
  tier3IrrHurdle: 18,
  tier4LpPercent: 50,
  tier4GpPercent: 50,

  // Operations
  holdPeriodYears: 5,
  year1NOI: 400000,
  noiGrowthPercent: 3,

  // Exit
  exitCapRate: 6.5,
  exitCostPercent: 3,
};

export const SYNDICATION_METRIC_EXPLANATIONS: Record<string, string> = {
  lpTotalDistributions:
    'Total cash returned to Limited Partners over the life of the investment, including return of capital, preferred return, and profit share.',
  lpIrr:
    'Internal Rate of Return for Limited Partners. The annualized return accounting for the timing of all cash flows in and out.',
  lpEquityMultiple:
    'Total LP distributions divided by LP equity invested. A 2.0x multiple means LPs doubled their money.',
  lpEquityContribution:
    'Total capital invested by Limited Partners. This is the LP share of total project capitalization.',
  gpTotalDistributions:
    'Total cash returned to the General Partner, including return of capital, management fees, and promote (profit share above hurdles).',
  gpIrr:
    'Internal Rate of Return for the General Partner. Includes acquisition fee, asset management fees, and promote distributions.',
  gpEquityMultiple:
    'Total GP distributions (including fees) divided by GP equity invested. GP typically achieves higher multiples due to promote.',
  gpEquityContribution:
    'Total capital invested by the General Partner. GPs typically invest 5-20% of total equity.',
  gpPromote:
    'GP promote is the profit share earned above the preferred return. This is the primary GP compensation for deal execution.',
  totalAcquisitionFees:
    'One-time fee paid to GP at closing for sourcing and structuring the deal. Typically 1-3% of total capitalization.',
  totalAssetManagementFees:
    'Annual fees paid to GP for managing the property operations. Typically 1-2% of total equity per year.',
  totalProjectProfit:
    'Total profit generated by the investment for all parties (LP + GP distributions minus total equity invested).',
  exitPrice:
    'Projected sale price based on the terminal NOI and exit cap rate. Higher NOI or lower cap rate increases the exit price.',
  totalEquity: 'Total equity invested in the project by all parties (LP + GP combined).',
  yearlyData: 'Year-by-year breakdown of NOI, fees, and distributions to LP and GP.',
  sensitivityData:
    'How LP and GP returns change with different exit cap rates. Lower exit cap rates mean higher sale prices and better returns.',
};
